const UPDATE_DB = 'UPDATE_DB';
const UPDATE_TABLE = 'UPDATE_TABLE';
const UPDATE_SEARCHOBJ = 'UPDATE_SEARCHOBJ';
const UPDATE_SELECTVIEW = 'UPDATE_SELECTVIEW';
const CREATE_TOAST = 'CREATE_TOAST';
const UPDATE_TOAST = 'UPDATE_TOAST';
const DESTROY_TOAST = 'DESTROY_TOAST';
const UPDATE_DB_OBJECT = 'UPDATE_DB_OBJECT';
const UPDATE_LAST_SELECT = 'UPDATE_LAST_SELECT';
const ADD_CANCEL_REQUEST = 'ADD_CANCEL_REQUEST';
const CLEAR_CANCEL_REQUEST = 'CLEAR_CANCEL_REQUEST';
const UPDATE_CHANGE_TREE = 'UPDATE_CHANGE_TREE';
const UPDATE_401_COUNT = 'UPDATE_401_COUNT';

export {
  CREATE_TOAST,
  UPDATE_DB,
  UPDATE_TABLE,
  UPDATE_SEARCHOBJ,
  UPDATE_SELECTVIEW,
  UPDATE_TOAST,
  DESTROY_TOAST,
  UPDATE_DB_OBJECT,
  UPDATE_LAST_SELECT,
  ADD_CANCEL_REQUEST,
  CLEAR_CANCEL_REQUEST,
  UPDATE_CHANGE_TREE,
  UPDATE_401_COUNT
}
